### ISSUE TITLE
Spanish documentation on official page?

### ISSUE THREAD

**Issue by esparta** [requests/requests-docs-es#2]
Do we need anything else to be published on the official page? The documentation is already up to date.

**Comment by carlosvargas** [comment]
I requested for the url http://es.python-requests.org/ to be created [here](https://github.com/kennethreitz/requests/issues/624#issuecomment-134332797). 

Also, I sent a PR for adding the link to the Spanish docs https://github.com/kennethreitz/requests/issues/2750.

**Comment by caizixian** [comment]
Close the issue now. kennethreitz/requests#2751
